package com.enums;

public enum EnumAsyncTask {
    DO_VALIDATE_IMEI,
    DO_SAVE_ABSEN,
    DO_UPDATE_ABSEN,
    DO_SAVE_ABSEN_DETAIL,
    GET_ABSEN_DATA,
    GET_LIST_BARANG,
    GET_LIST_BARANG_ORDER,
    GET_SERVER_VERSION,
    GET_SERVER_APK,
    DO_FIND_USER_BY_KODE_USER,
    DO_DELETE_SELECTED_BARANG,
    DO_CHECK_UPDATES,
    DO_CHECKOUT,
    DO_LOGIN,
}
